language: python

python:
    - 3.6

services:
  - docker

before_install:
  - docker build -t webserver ./webserver
  - docker build -t my-mysql ./my-mysql
  - docker run -d -p 3309:3306 --name my-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw my-mysql
  - docker run -d -p 5000:5000 --name webserver -e FLASK_APP=webserver.py webserver
  - docker ps -a

# install: 
#   - pip install -r webserver/requirements.txt

script:
  - python tests.py