language: python

python:
    - 3.6

services:
  - docker

before_install:
  - docker build -t my-mysql ./my-mysql
  - docker run -d -p 3309:3306 --name my-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw my-mysql
  - docker ps -a

install: 
  - pip install -r webserver/requirements.txt

before_script:
  - sleep 5

script:
  - export FLASK_APP=webserver.py 
  - cd webserver
  - flask run 
  - cd ..
  - python tests.py